# Generated by Django 3.2.9 on 2021-12-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('docid', models.AutoField(primary_key=True, serialize=False)),
                ('docname', models.CharField(max_length=100)),
                ('degree', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('tfid', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.CharField(max_length=100)),
                ('availtime', models.TimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointmentSystem.doctor')),
            ],
        ),
    ]
