# Generated by Django 3.2.9 on 2021-12-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeframe',
            old_name='availtime',
            new_name='endtime',
        ),
        migrations.AddField(
            model_name='timeframe',
            name='starttime',
            field=models.TimeField(null=True),
        ),
    ]
