# Generated by Django 3.2.9 on 2021-12-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentSystem', '0003_appointments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
    ]
