# Generated by Django 3.2.9 on 2021-12-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentSystem', '0004_rename_appointments_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointmentSystem.timeframe'),
        ),
    ]
